from pathlib import Path

from tools import clean_artifacts


def test_collect_generated_detects_cython_and_pyc(tmp_path: Path) -> None:
    cython_file = tmp_path / "example.c"
    cython_file.write_text("/* Generated by Cython */")
    pyc_file = tmp_path / "module.pyc"
    pyc_file.write_bytes(b"test")
    cache_dir = tmp_path / "__pycache__"
    cache_dir.mkdir()
    (cache_dir / "cached.pyc").write_bytes(b"cached")

    found = clean_artifacts.collect_generated(tmp_path)

    assert cython_file in found
    assert pyc_file in found
    assert cache_dir in found


def test_remove_paths_deletes_targets(tmp_path: Path) -> None:
    target = tmp_path / "generated.cpp"
    target.write_text("/* Generated by Cython */")
    report = tmp_path / "build_hash_report.json"
    report.write_text("{}")

    removed = clean_artifacts.remove_paths([target, report])

    assert target in removed and not target.exists()
    assert report in removed and not report.exists()


def test_collect_generated_ignores_manual_sources(tmp_path: Path) -> None:
    manual_cpp = tmp_path / "OrderBook.cpp"
    manual_cpp.write_text("// hand-written source file")

    found = clean_artifacts.collect_generated(tmp_path)

    assert manual_cpp not in found
