# -*- coding: utf-8 -*-
"""
Article 50 EU AI Act - Transparency Disclosure System.

This module implements the transparency requirements for AI systems
as mandated by Article 50 of the EU AI Act (Regulation (EU) 2024/1689).

Key Requirements:
- Article 50(1): AI interaction disclosure - Users must be informed they
  are interacting with an AI system
- Article 50(2): Synthetic content marking
- Article 50(3): Emotion recognition disclosure
- Article 50(4): Deep fake marking

References:
    - EU AI Act Article 50: https://artificialintelligenceact.eu/article/50/
    - Recital 132: Transparency for limited-risk AI
    - GPAI Code of Practice Chapter on Transparency
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional, Dict, List, Any
import hashlib
import json


class DisclosureType(Enum):
    """
    Article 50 disclosure categories.

    Each type corresponds to specific requirements under Article 50.
    """
    AI_INTERACTION = "ai_interaction"       # Art. 50(1) - Basic AI interaction
    SYNTHETIC_CONTENT = "synthetic_content"  # Art. 50(2) - AI-generated content
    EMOTION_RECOGNITION = "emotion_recognition"  # Art. 50(3) - Emotion detection
    DEEP_FAKE = "deep_fake"                 # Art. 50(4) - Manipulated media


class DisclosureContext(Enum):
    """
    Context where disclosure is shown to user.

    Different contexts may require different levels of disclosure.
    """
    REGISTRATION = "registration"
    STRATEGY_CREATION = "strategy_creation"
    LIVE_TRADING_ACTIVATION = "live_trading_activation"
    MODEL_OUTPUT = "model_output"
    API_RESPONSE = "api_response"
    DASHBOARD = "dashboard"
    REPORT_GENERATION = "report_generation"


class DisclosureLanguage(Enum):
    """Supported languages for disclosure texts."""
    ENGLISH = "en"
    RUSSIAN = "ru"
    GERMAN = "de"
    FRENCH = "fr"
    DUTCH = "nl"


@dataclass
class AIDisclosure:
    """
    Standard AI disclosure per Article 50.

    Must inform user that:
    1. They are interacting with an AI system
    2. The system uses machine learning (RL/PPO)
    3. Outputs are AI-generated predictions

    Attributes:
        disclosure_id: Unique identifier for tracking
        disclosure_type: Type of disclosure per Article 50
        context: Where/when the disclosure is shown
        timestamp: When disclosure was created
        user_id: User receiving the disclosure
        acknowledged: Whether user has acknowledged
        acknowledgment_timestamp: When user acknowledged
        ai_system_name: Name of the AI system
        ai_system_type: Type/architecture of the AI
        ai_purpose: Purpose of the AI system
    """
    disclosure_id: str
    disclosure_type: DisclosureType
    context: DisclosureContext
    timestamp: datetime
    user_id: str
    acknowledged: bool = False
    acknowledgment_timestamp: Optional[datetime] = None

    # Required content per Article 50
    ai_system_name: str = "Distributional PPO Trading Model"
    ai_system_type: str = "Reinforcement Learning"
    ai_purpose: str = "Trading signal generation and portfolio optimization"

    # Metadata for audit trail
    version: str = "1.0"
    ip_address: Optional[str] = None
    user_agent: Optional[str] = None

    def generate_disclosure_text(self, language: str = "en") -> Dict[str, str]:
        """
        Generate Article 50 compliant disclosure text.

        Args:
            language: Language code (en, ru, de, fr, nl)

        Returns:
            Dictionary with header, body, and acknowledge text
        """
        texts = {
            "en": {
                "header": "AI SYSTEM DISCLOSURE",
                "subheader": "EU AI Act Article 50 Notice",
                "body": (
                    "This service uses an Artificial Intelligence (AI) system "
                    "based on machine learning technology (Reinforcement Learning). "
                    "Trading signals, predictions, and portfolio recommendations are "
                    "generated by the AI model, not by human analysts.\n\n"
                    "The AI system has limitations and may produce inaccurate "
                    "predictions. Historical performance does not guarantee future "
                    "results. You retain full responsibility for all trading decisions."
                ),
                "acknowledge": "I understand that I am interacting with an AI system",
                "model_info": f"AI System: {self.ai_system_name}",
                "footer": "This disclosure is provided pursuant to Article 50 of Regulation (EU) 2024/1689"
            },
            "ru": {
                "header": "РАСКРЫТИЕ ИНФОРМАЦИИ ОБ ИИ-СИСТЕМЕ",
                "subheader": "Уведомление по Статье 50 EU AI Act",
                "body": (
                    "Данный сервис использует систему искусственного интеллекта (ИИ) "
                    "на основе технологии машинного обучения (Reinforcement Learning). "
                    "Торговые сигналы, прогнозы и рекомендации по портфелю генерируются "
                    "ИИ-моделью, а не аналитиками-людьми.\n\n"
                    "ИИ-система имеет ограничения и может давать неточные прогнозы. "
                    "Исторические результаты не гарантируют будущую доходность. "
                    "Вы несёте полную ответственность за все торговые решения."
                ),
                "acknowledge": "Я понимаю, что взаимодействую с ИИ-системой",
                "model_info": f"ИИ-система: {self.ai_system_name}",
                "footer": "Данное раскрытие предоставлено в соответствии со Статьёй 50 Регламента (ЕС) 2024/1689"
            },
            "de": {
                "header": "KI-SYSTEM OFFENLEGUNG",
                "subheader": "EU AI Act Artikel 50 Mitteilung",
                "body": (
                    "Dieser Dienst verwendet ein System der Künstlichen Intelligenz (KI) "
                    "basierend auf maschinellem Lernen (Reinforcement Learning). "
                    "Handelssignale, Vorhersagen und Portfolioempfehlungen werden "
                    "vom KI-Modell generiert, nicht von menschlichen Analysten.\n\n"
                    "Das KI-System hat Einschränkungen und kann ungenaue Vorhersagen "
                    "treffen. Vergangene Leistungen garantieren keine zukünftigen "
                    "Ergebnisse. Sie tragen die volle Verantwortung für alle Handelsentscheidungen."
                ),
                "acknowledge": "Ich verstehe, dass ich mit einem KI-System interagiere",
                "model_info": f"KI-System: {self.ai_system_name}",
                "footer": "Diese Offenlegung erfolgt gemäß Artikel 50 der Verordnung (EU) 2024/1689"
            },
            "fr": {
                "header": "DIVULGATION DU SYSTEME D'IA",
                "subheader": "Avis Article 50 EU AI Act",
                "body": (
                    "Ce service utilise un système d'Intelligence Artificielle (IA) "
                    "basé sur l'apprentissage automatique (Reinforcement Learning). "
                    "Les signaux de trading, les prédictions et les recommandations "
                    "de portefeuille sont générés par le modèle d'IA, pas par des "
                    "analystes humains.\n\n"
                    "Le système d'IA a des limitations et peut produire des prédictions "
                    "inexactes. Les performances passées ne garantissent pas les "
                    "résultats futurs. Vous assumez l'entière responsabilité de toutes "
                    "les décisions de trading."
                ),
                "acknowledge": "Je comprends que j'interagis avec un système d'IA",
                "model_info": f"Système d'IA: {self.ai_system_name}",
                "footer": "Cette divulgation est fournie conformément à l'article 50 du règlement (UE) 2024/1689"
            },
            "nl": {
                "header": "AI-SYSTEEM BEKENDMAKING",
                "subheader": "EU AI Act Artikel 50 Kennisgeving",
                "body": (
                    "Deze service maakt gebruik van een Kunstmatige Intelligentie (AI) "
                    "systeem gebaseerd op machine learning technologie (Reinforcement Learning). "
                    "Handelssignalen, voorspellingen en portfolioaanbevelingen worden "
                    "gegenereerd door het AI-model, niet door menselijke analisten.\n\n"
                    "Het AI-systeem heeft beperkingen en kan onnauwkeurige voorspellingen "
                    "produceren. Historische prestaties garanderen geen toekomstige "
                    "resultaten. U bent volledig verantwoordelijk voor alle handelsbeslissingen."
                ),
                "acknowledge": "Ik begrijp dat ik interactie heb met een AI-systeem",
                "model_info": f"AI-systeem: {self.ai_system_name}",
                "footer": "Deze bekendmaking wordt verstrekt op grond van artikel 50 van Verordening (EU) 2024/1689"
            }
        }
        return texts.get(language, texts["en"])

    def to_dict(self) -> Dict[str, Any]:
        """Convert disclosure to dictionary for serialization."""
        return {
            "disclosure_id": self.disclosure_id,
            "disclosure_type": self.disclosure_type.value,
            "context": self.context.value,
            "timestamp": self.timestamp.isoformat(),
            "user_id": self.user_id,
            "acknowledged": self.acknowledged,
            "acknowledgment_timestamp": (
                self.acknowledgment_timestamp.isoformat()
                if self.acknowledgment_timestamp else None
            ),
            "ai_system_name": self.ai_system_name,
            "ai_system_type": self.ai_system_type,
            "ai_purpose": self.ai_purpose,
            "version": self.version,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "AIDisclosure":
        """Create disclosure from dictionary."""
        return cls(
            disclosure_id=data["disclosure_id"],
            disclosure_type=DisclosureType(data["disclosure_type"]),
            context=DisclosureContext(data["context"]),
            timestamp=datetime.fromisoformat(data["timestamp"]),
            user_id=data["user_id"],
            acknowledged=data.get("acknowledged", False),
            acknowledgment_timestamp=(
                datetime.fromisoformat(data["acknowledgment_timestamp"])
                if data.get("acknowledgment_timestamp") else None
            ),
            ai_system_name=data.get("ai_system_name", "Distributional PPO Trading Model"),
            ai_system_type=data.get("ai_system_type", "Reinforcement Learning"),
            ai_purpose=data.get("ai_purpose", "Trading signal generation"),
            version=data.get("version", "1.0"),
        )


@dataclass
class DisclosureRequirement:
    """
    Defines when disclosure is required per Article 50.

    Attributes:
        context: The context requiring disclosure
        required: Whether disclosure is mandatory
        reason: Why disclosure is required
        article_reference: The specific article/recital reference
        blocking: Whether to block access until acknowledged
    """
    context: DisclosureContext
    required: bool
    reason: str
    article_reference: str
    blocking: bool = True


# Standard disclosure requirements per Article 50
DISCLOSURE_REQUIREMENTS: List[DisclosureRequirement] = [
    DisclosureRequirement(
        context=DisclosureContext.REGISTRATION,
        required=True,
        reason="User begins interaction with AI-powered platform",
        article_reference="Article 50(1)",
        blocking=True
    ),
    DisclosureRequirement(
        context=DisclosureContext.STRATEGY_CREATION,
        required=True,
        reason="AI system assists in strategy development",
        article_reference="Article 50(1)",
        blocking=False
    ),
    DisclosureRequirement(
        context=DisclosureContext.LIVE_TRADING_ACTIVATION,
        required=True,
        reason="AI system will execute real trades with financial impact",
        article_reference="Article 50(1)",
        blocking=True
    ),
    DisclosureRequirement(
        context=DisclosureContext.MODEL_OUTPUT,
        required=True,
        reason="AI-generated trading signals are presented",
        article_reference="Article 50(1), Article 50(2)",
        blocking=False
    ),
    DisclosureRequirement(
        context=DisclosureContext.API_RESPONSE,
        required=True,
        reason="Programmatic access to AI outputs",
        article_reference="Article 50(1), Recital 132",
        blocking=False
    ),
    DisclosureRequirement(
        context=DisclosureContext.DASHBOARD,
        required=True,
        reason="AI-generated analytics displayed to user",
        article_reference="Article 50(1)",
        blocking=False
    ),
    DisclosureRequirement(
        context=DisclosureContext.REPORT_GENERATION,
        required=True,
        reason="AI-generated content in reports",
        article_reference="Article 50(2)",
        blocking=False
    ),
]


@dataclass
class DisclosureAuditRecord:
    """Audit record for disclosure tracking."""
    record_id: str
    disclosure_id: str
    user_id: str
    action: str  # created, shown, acknowledged, revoked
    timestamp: datetime
    context: DisclosureContext
    metadata: Dict[str, Any] = field(default_factory=dict)


class TransparencyDisclosureManager:
    """
    Manages Article 50 transparency disclosures.

    Responsibilities:
    1. Generate disclosure content in multiple languages
    2. Track user acknowledgments
    3. Provide audit trail for compliance verification
    4. Add API response headers per Article 50
    5. Verify disclosure requirements are met

    Example:
        >>> manager = create_transparency_manager()
        >>> disclosure = manager.create_disclosure("user123", DisclosureContext.REGISTRATION)
        >>> text = disclosure.generate_disclosure_text("en")
        >>> print(text["header"])
        AI SYSTEM DISCLOSURE
    """

    def __init__(self, storage_backend: Optional[Dict] = None):
        """
        Initialize the transparency disclosure manager.

        Args:
            storage_backend: Optional storage backend for persistence
        """
        self.storage = storage_backend or {}
        self.disclosures: Dict[str, AIDisclosure] = {}
        self.audit_log: List[DisclosureAuditRecord] = []
        self._user_disclosures: Dict[str, List[str]] = {}  # user_id -> disclosure_ids

    def create_disclosure(
        self,
        user_id: str,
        context: DisclosureContext,
        disclosure_type: DisclosureType = DisclosureType.AI_INTERACTION,
        ip_address: Optional[str] = None,
        user_agent: Optional[str] = None
    ) -> AIDisclosure:
        """
        Create new disclosure for user context.

        Args:
            user_id: Unique user identifier
            context: Context where disclosure is shown
            disclosure_type: Type of disclosure per Article 50
            ip_address: Optional IP for audit trail
            user_agent: Optional user agent for audit trail

        Returns:
            AIDisclosure instance
        """
        disclosure_id = self._generate_id(user_id, context)

        disclosure = AIDisclosure(
            disclosure_id=disclosure_id,
            disclosure_type=disclosure_type,
            context=context,
            timestamp=datetime.utcnow(),
            user_id=user_id,
            ip_address=ip_address,
            user_agent=user_agent
        )

        self.disclosures[disclosure_id] = disclosure

        # Track user's disclosures
        if user_id not in self._user_disclosures:
            self._user_disclosures[user_id] = []
        self._user_disclosures[user_id].append(disclosure_id)

        # Audit log
        self._log_action(disclosure_id, user_id, "created", context)

        return disclosure

    def record_acknowledgment(
        self,
        disclosure_id: str,
        user_id: str,
        ip_address: Optional[str] = None,
        user_agent: Optional[str] = None
    ) -> bool:
        """
        Record user acknowledgment of AI disclosure.

        Args:
            disclosure_id: The disclosure being acknowledged
            user_id: User acknowledging the disclosure
            ip_address: Optional IP for audit trail
            user_agent: Optional user agent for audit trail

        Returns:
            True if acknowledgment recorded, False if failed
        """
        if disclosure_id not in self.disclosures:
            return False

        disclosure = self.disclosures[disclosure_id]

        # Verify user owns this disclosure
        if disclosure.user_id != user_id:
            return False

        disclosure.acknowledged = True
        disclosure.acknowledgment_timestamp = datetime.utcnow()

        # Audit log
        self._log_action(
            disclosure_id,
            user_id,
            "acknowledged",
            disclosure.context,
            metadata={"ip_address": ip_address, "user_agent": user_agent}
        )

        return True

    def check_disclosure_required(
        self,
        user_id: str,
        context: DisclosureContext
    ) -> bool:
        """
        Check if disclosure is required for this context.

        Args:
            user_id: User to check
            context: Context to check

        Returns:
            True if disclosure is required, False otherwise
        """
        # Find requirement for this context
        requirement = self._get_requirement(context)
        if not requirement or not requirement.required:
            return False

        # Check if already acknowledged
        disclosure_id = self._generate_id(user_id, context)
        if disclosure_id in self.disclosures:
            return not self.disclosures[disclosure_id].acknowledged

        return True

    def get_user_disclosures(
        self,
        user_id: str,
        context: Optional[DisclosureContext] = None
    ) -> List[AIDisclosure]:
        """
        Get all disclosures for a user.

        Args:
            user_id: User to get disclosures for
            context: Optional filter by context

        Returns:
            List of AIDisclosure instances
        """
        disclosure_ids = self._user_disclosures.get(user_id, [])
        disclosures = [
            self.disclosures[did]
            for did in disclosure_ids
            if did in self.disclosures
        ]

        if context:
            disclosures = [d for d in disclosures if d.context == context]

        return disclosures

    def get_api_headers(self) -> Dict[str, str]:
        """
        Return HTTP headers for API responses per Article 50.

        These headers must be included in all API responses that
        return AI-generated content.

        Returns:
            Dictionary of headers to add to API responses
        """
        return {
            "X-AI-System": "true",
            "X-AI-Model": "Distributional-PPO-v1",
            "X-AI-Model-Type": "Reinforcement-Learning",
            "X-AI-Disclosure": "This response is generated by an AI system",
            "X-AI-Act-Compliance": "Article-50",
            "X-AI-Provider": "AI-Powered-Quantitative-Research-Platform",
        }

    def get_api_response_metadata(self) -> Dict[str, Any]:
        """
        Get metadata to include in API response body.

        Returns:
            Dictionary with AI system metadata
        """
        return {
            "_ai_disclosure": {
                "is_ai_generated": True,
                "model_name": "Distributional PPO Trading Model",
                "model_type": "Reinforcement Learning",
                "compliance": "EU AI Act Article 50",
                "notice": "This content is generated by an AI system",
                "timestamp": datetime.utcnow().isoformat(),
            }
        }

    def verify_compliance(self, user_id: str) -> Dict[str, Any]:
        """
        Verify Article 50 compliance status for a user.

        Args:
            user_id: User to verify

        Returns:
            Dictionary with compliance status
        """
        user_disclosures = self.get_user_disclosures(user_id)

        # Check each required context
        compliance_status = {}
        for req in DISCLOSURE_REQUIREMENTS:
            if not req.required:
                continue

            context_disclosures = [
                d for d in user_disclosures
                if d.context == req.context
            ]

            if context_disclosures:
                latest = max(context_disclosures, key=lambda d: d.timestamp)
                compliance_status[req.context.value] = {
                    "disclosed": True,
                    "acknowledged": latest.acknowledged,
                    "timestamp": latest.timestamp.isoformat(),
                    "blocking": req.blocking and not latest.acknowledged,
                }
            else:
                compliance_status[req.context.value] = {
                    "disclosed": False,
                    "acknowledged": False,
                    "timestamp": None,
                    "blocking": req.blocking,
                }

        all_acknowledged = all(
            s.get("acknowledged", False)
            for s in compliance_status.values()
        )

        return {
            "user_id": user_id,
            "article_50_compliant": all_acknowledged,
            "contexts": compliance_status,
            "verification_timestamp": datetime.utcnow().isoformat(),
        }

    def get_audit_trail(
        self,
        user_id: Optional[str] = None,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None
    ) -> List[Dict[str, Any]]:
        """
        Get audit trail for disclosures.

        Args:
            user_id: Optional filter by user
            start_date: Optional start date filter
            end_date: Optional end date filter

        Returns:
            List of audit records
        """
        records = self.audit_log

        if user_id:
            records = [r for r in records if r.user_id == user_id]
        if start_date:
            records = [r for r in records if r.timestamp >= start_date]
        if end_date:
            records = [r for r in records if r.timestamp <= end_date]

        return [
            {
                "record_id": r.record_id,
                "disclosure_id": r.disclosure_id,
                "user_id": r.user_id,
                "action": r.action,
                "timestamp": r.timestamp.isoformat(),
                "context": r.context.value,
                "metadata": r.metadata,
            }
            for r in records
        ]

    def _generate_id(self, user_id: str, context: DisclosureContext) -> str:
        """Generate unique disclosure ID."""
        data = f"{user_id}:{context.value}"
        return hashlib.sha256(data.encode()).hexdigest()[:16]

    def _get_requirement(
        self,
        context: DisclosureContext
    ) -> Optional[DisclosureRequirement]:
        """Get requirement for a context."""
        for req in DISCLOSURE_REQUIREMENTS:
            if req.context == context:
                return req
        return None

    def _log_action(
        self,
        disclosure_id: str,
        user_id: str,
        action: str,
        context: DisclosureContext,
        metadata: Optional[Dict[str, Any]] = None
    ) -> None:
        """Log action to audit trail."""
        record = DisclosureAuditRecord(
            record_id=hashlib.sha256(
                f"{disclosure_id}:{action}:{datetime.utcnow().isoformat()}".encode()
            ).hexdigest()[:16],
            disclosure_id=disclosure_id,
            user_id=user_id,
            action=action,
            timestamp=datetime.utcnow(),
            context=context,
            metadata=metadata or {}
        )
        self.audit_log.append(record)


class SyntheticContentMarker:
    """
    Article 50(2) - Synthetic Content Marking.

    Marks AI-generated content (reports, analysis, etc.) as synthetic.
    """

    MARKER_PREFIX = "[AI-GENERATED]"

    @staticmethod
    def mark_content(content: str, include_footer: bool = True) -> str:
        """
        Mark content as AI-generated.

        Args:
            content: The content to mark
            include_footer: Whether to add footer notice

        Returns:
            Content with AI generation markers
        """
        marked = f"{SyntheticContentMarker.MARKER_PREFIX}\n{content}"

        if include_footer:
            footer = (
                "\n\n---\n"
                "*This content was generated by an AI system. "
                "Per Article 50(2) of the EU AI Act, AI-generated "
                "content must be clearly marked.*"
            )
            marked += footer

        return marked

    @staticmethod
    def add_metadata(data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Add AI generation metadata to a data structure.

        Args:
            data: Dictionary to add metadata to

        Returns:
            Dictionary with metadata added
        """
        data["_synthetic_content"] = {
            "is_ai_generated": True,
            "generator": "Distributional PPO Trading Model",
            "compliance": "EU AI Act Article 50(2)",
            "generated_at": datetime.utcnow().isoformat(),
        }
        return data

    @staticmethod
    def is_marked(content: str) -> bool:
        """Check if content is already marked."""
        return content.startswith(SyntheticContentMarker.MARKER_PREFIX)


def create_transparency_manager(
    storage_backend: Optional[Dict] = None
) -> TransparencyDisclosureManager:
    """
    Create configured transparency manager.

    Factory function for creating TransparencyDisclosureManager instances.

    Args:
        storage_backend: Optional storage backend for persistence

    Returns:
        Configured TransparencyDisclosureManager instance
    """
    return TransparencyDisclosureManager(storage_backend=storage_backend)


def get_disclosure_requirements() -> List[DisclosureRequirement]:
    """
    Get all disclosure requirements.

    Returns:
        List of DisclosureRequirement instances
    """
    return DISCLOSURE_REQUIREMENTS.copy()


def validate_disclosure_text(
    disclosure: AIDisclosure,
    language: str = "en"
) -> Dict[str, bool]:
    """
    Validate that disclosure text meets Article 50 requirements.

    Args:
        disclosure: Disclosure to validate
        language: Language to validate

    Returns:
        Dictionary with validation results
    """
    text = disclosure.generate_disclosure_text(language)

    checks = {
        "has_header": bool(text.get("header")),
        "has_body": bool(text.get("body")),
        "has_acknowledge": bool(text.get("acknowledge")),
        "mentions_ai": "AI" in text.get("body", "") or "Artificial Intelligence" in text.get("body", ""),
        "mentions_ml": (
            "machine learning" in text.get("body", "").lower() or
            "maschinell" in text.get("body", "").lower() or
            "apprentissage" in text.get("body", "").lower() or
            "машинного обучения" in text.get("body", "").lower()
        ),
        "mentions_limitations": "limitation" in text.get("body", "").lower() or "ограничения" in text.get("body", "").lower(),
        "mentions_responsibility": "responsibility" in text.get("body", "").lower() or "ответственность" in text.get("body", "").lower(),
    }

    checks["all_valid"] = all(checks.values())

    return checks
